version: '3.1'
services:
  redis:
    image: 'bitnami/redis:7.4'
    networks:
      - hmpps_int
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  auth-wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    restart: always
    ports:
      - '9090:8080'
    volumes:
      - ./wiremock/mappings/auth:/home/wiremock/mappings
  allocation-wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    restart: always
    ports:
      - '9091:8080'
    volumes:
      - ./wiremock/mappings/allocation:/home/wiremock/mappings
  workload-wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    restart: always
    ports:
      - '9092:8080'
    volumes:
      - ./wiremock/mappings/workload:/home/wiremock/mappings
  probation-estate-wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    restart: always
    ports:
      - '9093:8080'
    volumes:
      - ./wiremock/mappings/probation-estate:/home/wiremock/mappings
  user-preference-wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    restart: always
    ports:
      - '9094:8080'
    volumes:
      - ./wiremock/mappings/user-preference:/home/wiremock/mappings
  staff-lookup-wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    restart: always
    ports:
      - '9095:8080'
  manage-users-wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    restart: always
    ports:
      - '9096:8080'
    volumes:
      - ./wiremock/mappings/user:/home/wiremock/mappings
networks:
  hmpps_int:
