version: '3.1'
services:

  redis:
    image: 'bitnami/redis:5.0'
    networks:
      - hmpps_int
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  allocation-wiremock:
    image: rodolpheche/wiremock
    networks:
    - hmpps_int
    restart: always
    ports:
      - "9091:8080"
  workload-wiremock:
    image: rodolpheche/wiremock
    networks:
    - hmpps_int
    restart: always
    ports:
      - "9092:8080"

networks:
  hmpps_int:
