version: '3.1'
services:
  redis:
    image: 'redis/redis-stack-server:7.2.0-v18'
    networks:
      - hmpps_int
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  auth-wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    restart: always
    ports:
      - '9090:8080'
  allocation-wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    restart: always
    ports:
      - '9091:8080'
  workload-wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    restart: always
    ports:
      - '9092:8080'
  probation-estate-wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    restart: always
    ports:
      - '9093:8080'
  user-preference-wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    restart: always
    ports:
      - '9094:8080'
  staff-lookup-wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    restart: always
    ports:
      - '9095:8080'
  manage-users-wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    restart: always
    ports:
      - '9096:8080'

networks:
  hmpps_int:
