apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: manage-a-workforce-ui-ingress-alerts-test
  labels:
    {{- include "generic-prometheus-alerts.labels" . | nindent 4 }}
spec:
  groups:
    - name: manage-a-workforce-ui-ingress-alerts-test
      rules:
        - alert: 5xxErrorResponses
          annotations:
            message: Ingress workforce-management-dev/manage-a-workforce-ui-alert-tests is serving 5xx responses.
            runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/MaS/pages/3386245142/Workload+Measurement+Tool+WMT
            dashboard_url: https://dsdmoj.atlassian.net/wiki/spaces/MaS/pages/3386245142/Workload+Measurement+Tool+WMT
          expr: |-
            avg(rate(nginx_ingress_controller_requests{exported_namespace=~"workforce-management-dev", ingress=~"manage-a-workforce-ui-v1-2", status=~"5.*"}[4m]) * 60 > 0) by (ingress, exported_namespace)
          for: 1m
          labels:
            severity: {{ .Values.alertSeverity }}