generic-service:
  nameOverride: manage-a-workforce-ui

  replicaCount: 2

  image:
    repository: quay.io/hmpps/manage-a-workforce-ui
    tag: app_version # override at deployment time
    port: 3000

  controller:
    service:
      ports:
        https: 443

  ingress:
    enabled: true
    modsecurity_enabled: true
    v1_2_enabled: true
    v0_47_enabled: false
    host: app-hostname.local # override per environment
    tlsSecretName: manage-a-workforce-ui-cert
    path: /
    contextColour: green
    modsecurity_snippet: |
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=manage-a-workforce"
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleRemoveById 942430
      SecRuleRemoveById 942210
      SecRuleRemoveById 950100
      SecRuleUpdateTargetById 942440 "!REQUEST_COOKIES:/connect.sid/"
      SecRuleUpdateTargetById 942450 "!REQUEST_COOKIES:/connect.sid/"
      SecRuleUpdateTargetById 930120 "!REQUEST_COOKIES:/connect.sid/"
      SecRuleUpdateTargetById 942210 "!REQUEST_COOKIES:/connect.sid/"
      SecRule REQUEST_URI "@endsWith /confirm-allocation" \
        "id:1004,\
        phase:1,\
        pass,\
        nolog,\
        ctl:ruleRemoveTargetByTag=attack-sqli;ARGS:instructions"
      SecRule REQUEST_URI "@endsWith /confirm-allocation" \
        "id:1005,\
        phase:1,\
        pass,\
        nolog,\
        ctl:ruleRemoveTargetByTag=platform-windows;ARGS:instructions"
      SecAction \
        "id:900000,\
        phase:1,\
        nolog,\
        pass,\
        t:none,\
        setvar:tx.paranoia_level=2"
      SecRule REQUEST_URI "@endsWith /confirm-allocation" \
        "id:1006,\
        phase:1,\
        pass,\
        nolog,\
        ctl:ruleRemoveTargetByTag=attack-rce;ARGS:instructions"
      SecRule REQUEST_URI "@endsWith /confirm-allocation" \
        "id:1007,\
        phase:2,\
        pass,\
        nolog,\
        ctl:ruleRemoveById=921110"
      SecRuleUpdateTargetById 942440 "!ARGS:_csrf"
      SecRule REQUEST_URI "@endsWith /decision-evidencing" \
        "id:1008,\
        phase:1,\
        pass,\
        nolog,\
        ctl:ruleRemoveTargetByTag=attack-sqli;ARGS:evidenceText"
      SecRule REQUEST_URI "@endsWith /decision-evidencing" \
        "id:1009,\
        phase:1,\
        pass,\
        nolog,\
        ctl:ruleRemoveTargetByTag=language-php;ARGS:evidenceText"
      SecRule REQUEST_URI "@endsWith /confirm-allocation" \
        "id:1010,\
        phase:1,\
        pass,\
        nolog,\
        ctl:ruleRemoveTargetByTag=language-php;ARGS:instructions"
      SecRule REQUEST_URI "@endsWith /decision-evidencing" \
        "id:1011,\
        phase:1,\
        pass,\
        nolog,\
        ctl:ruleRemoveTargetByTag=platform-windows;ARGS:evidenceText"
      SecRule REQUEST_URI "@endsWith /decision-evidencing" \
        "id:1012,\
        phase:1,\
        pass,\
        nolog,\
        ctl:ruleRemoveTargetByTag=attack-rce;ARGS:evidenceText"
      SecRule REQUEST_URI "@endsWith /decision-evidencing" \
        "id:1013,\
        phase:1,\
        pass,\
        nolog,\
        ctl:ruleRemoveTargetByTag=attack-rfi;ARGS:evidenceText"

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    SHOW_NOTIFICATION: "false"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    manage-a-workforce-ui:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "AUTH_API_CLIENT_ID"
      API_CLIENT_SECRET: "AUTH_API_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
      GOOGLE_ANALYTICS_KEY: "GOOGLE_ANALYTICS_KEY"
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

  allowlist:
    groups:
      - internal
      - prisons
      - probation

generic-prometheus-alerts:
  targetApplication: manage-a-workforce-ui
  alertSeverity: hmpps-tier
