import { SuperAgentRequest } from 'superagent'
import type TeamWorkloadData from '../../server/models/TeamWorkloadData'
import { stubForWorkload } from './wiremock'

const teamWorkload: TeamWorkloadData = {
  N03F01: {
    teams: [
      {
        code: 'N03A020',
        name: {
          forename: 'Coco',
          surname: 'Pint',
          combinedName: 'Coco Pint',
        },
        email: 'simulate-delivered@notifications.service.gov.uk',
        grade: 'PO',
        workload: 10,
        casesPastWeek: 11,
        communityCases: 1,
        custodyCases: 1,
        licenseCases: 2,
        allocatedCasesPastWeek: 1,
        reallocatedCasesPastWeek: 0,
        ispsDueInNext14Days: 3,
        activeCases: 14,
        contactSuspendedCases: 0,
        custodyReleasesInNext7Days: 1,
        paroleReportsInNext28Days: 2,
        otherReportsInNext14Days: 1,
        tierCaseTotals: {
          untiered: 0,
          a: 2,
          b: 3,
          c: 4,
          d: 1,
          as: 0,
          bs: 1,
          cs: 2,
          ds: 1,
        },
      },
      {
        code: 'N03A016',
        name: {
          forename: 'Carlo',
          surname: 'Veo',
          combinedName: 'Carlo Veo',
        },
        email: 'carlo.veo@digital.justice.gov.uk',
        grade: 'PO',
        workload: 20,
        casesPastWeek: 12,
        communityCases: 2,
        custodyCases: 2,
        licenseCases: 3,
        allocatedCasesPastWeek: 2,
        reallocatedCasesPastWeek: 1,
        ispsDueInNext14Days: 4,
        activeCases: 15,
        contactSuspendedCases: 1,
        custodyReleasesInNext7Days: 0,
        paroleReportsInNext28Days: 1,
        otherReportsInNext14Days: 2,
        tierCaseTotals: {
          untiered: 1,
          a: 1,
          b: 4,
          c: 3,
          d: 2,
          as: 1,
          bs: 0,
          cs: 1,
          ds: 2,
        },
      },
      {
        code: 'N01A022',
        name: {
          forename: 'Katie',
          surname: 'Cawthorne',
          combinedName: 'Katie Cawthorne',
        },
        email: 'katie.cawthorne@digital.justice.gov.uk',
        grade: 'PO',
        workload: 30,
        casesPastWeek: 13,
        communityCases: 3,
        custodyCases: 3,
        licenseCases: 1,
        allocatedCasesPastWeek: 3,
        reallocatedCasesPastWeek: 1,
        ispsDueInNext14Days: 2,
        activeCases: 16,
        contactSuspendedCases: 0,
        custodyReleasesInNext7Days: 2,
        paroleReportsInNext28Days: 0,
        otherReportsInNext14Days: 3,
        tierCaseTotals: {
          untiered: 0,
          a: 3,
          b: 2,
          c: 5,
          d: 1,
          as: 2,
          bs: 1,
          cs: 0,
          ds: 1,
        },
      },
      {
        code: 'N04A135',
        name: {
          forename: 'Test',
          surname: 'User',
          combinedName: 'Test User',
        },
        grade: 'PO',
        workload: 40,
        casesPastWeek: 14,
        communityCases: 4,
        custodyCases: 4,
        licenseCases: 0,
        allocatedCasesPastWeek: 4,
        reallocatedCasesPastWeek: 2,
        ispsDueInNext14Days: 1,
        activeCases: 17,
        contactSuspendedCases: 2,
        custodyReleasesInNext7Days: 1,
        paroleReportsInNext28Days: 3,
        otherReportsInNext14Days: 0,
        tierCaseTotals: {
          untiered: 2,
          a: 2,
          b: 1,
          c: 4,
          d: 2,
          as: 1,
          bs: 1,
          cs: 2,
          ds: 0,
        },
      },
      {
        code: 'N54A022',
        name: {
          forename: 'AutomatedTestUser',
          surname: 'AutomatedTestUser',
          combinedName: 'AutomatedTestUser AutomatedTestUser',
        },
        email: 'simulate-delivered@notifications.service.gov.uk',
        grade: 'PSO',
        workload: 50,
        casesPastWeek: 15,
        communityCases: 5,
        custodyCases: 5,
        licenseCases: 4,
        allocatedCasesPastWeek: 5,
        reallocatedCasesPastWeek: 2,
        ispsDueInNext14Days: 5,
        activeCases: 18,
        contactSuspendedCases: 0,
        custodyReleasesInNext7Days: 2,
        paroleReportsInNext28Days: 2,
        otherReportsInNext14Days: 1,
        tierCaseTotals: {
          untiered: 1,
          a: 4,
          b: 3,
          c: 2,
          d: 1,
          as: 0,
          bs: 2,
          cs: 1,
          ds: 0,
        },
      },
      {
        code: 'N07B656',
        name: {
          forename: 'Natalie',
          surname: 'Wood',
          combinedName: 'Natalie Wood',
        },
        email: 'natalie.wood@digital.justice.gov.uk',
        grade: 'PO',
        workload: 60,
        casesPastWeek: 16,
        communityCases: 6,
        custodyCases: 6,
        licenseCases: 5,
        allocatedCasesPastWeek: 6,
        reallocatedCasesPastWeek: 3,
        ispsDueInNext14Days: 3,
        activeCases: 19,
        contactSuspendedCases: 1,
        custodyReleasesInNext7Days: 0,
        paroleReportsInNext28Days: 4,
        otherReportsInNext14Days: 2,
        tierCaseTotals: {
          untiered: 0,
          a: 3,
          b: 5,
          c: 1,
          d: 2,
          as: 1,
          bs: 0,
          cs: 3,
          ds: 1,
        },
      },
      {
        code: 'N07B743',
        name: {
          forename: 'Paul',
          surname: 'McPhee',
          combinedName: 'Paul McPhee',
        },
        email: 'paul.mcphee@digital.justice.gov.uk',
        grade: 'PO',
        workload: 70,
        casesPastWeek: 17,
        communityCases: 7,
        custodyCases: 7,
        licenseCases: 2,
        allocatedCasesPastWeek: 7,
        reallocatedCasesPastWeek: 3,
        ispsDueInNext14Days: 6,
        activeCases: 20,
        contactSuspendedCases: 1,
        custodyReleasesInNext7Days: 1,
        paroleReportsInNext28Days: 1,
        otherReportsInNext14Days: 4,
        tierCaseTotals: {
          untiered: 1,
          a: 2,
          b: 4,
          c: 4,
          d: 1,
          as: 2,
          bs: 1,
          cs: 1,
          ds: 1,
        },
      },
      {
        code: 'N03F030',
        name: {
          forename: 'Robert',
          surname: 'King',
          combinedName: 'Robert King',
        },
        email: 'robert.king@digital.justice.gov.uk',
        grade: 'PO',
        workload: 80,
        casesPastWeek: 18,
        communityCases: 8,
        custodyCases: 8,
        licenseCases: 6,
        allocatedCasesPastWeek: 8,
        reallocatedCasesPastWeek: 4,
        ispsDueInNext14Days: 2,
        activeCases: 21,
        contactSuspendedCases: 0,
        custodyReleasesInNext7Days: 2,
        paroleReportsInNext28Days: 3,
        otherReportsInNext14Days: 1,
        tierCaseTotals: {
          untiered: 0,
          a: 5,
          b: 2,
          c: 3,
          d: 3,
          as: 0,
          bs: 2,
          cs: 2,
          ds: 1,
        },
      },
      {
        code: 'N57A029',
        name: {
          forename: 'Leigh',
          surname: 'Christie',
          combinedName: 'Leigh Christie',
        },
        email: 'leigh.christie@digital.justice.gov.uk',
        grade: 'PO',
        workload: 90,
        casesPastWeek: 19,
        communityCases: 9,
        custodyCases: 9,
        licenseCases: 3,
        allocatedCasesPastWeek: 9,
        reallocatedCasesPastWeek: 4,
        ispsDueInNext14Days: 7,
        activeCases: 22,
        contactSuspendedCases: 2,
        custodyReleasesInNext7Days: 0,
        paroleReportsInNext28Days: 2,
        otherReportsInNext14Days: 2,
        tierCaseTotals: {
          untiered: 2,
          a: 3,
          b: 3,
          c: 5,
          d: 0,
          as: 1,
          bs: 1,
          cs: 2,
          ds: 2,
        },
      },
      {
        code: 'N03A019',
        name: {
          forename: 'Derek',
          surname: 'Pint',
          combinedName: 'Derek Pint',
        },
        email: 'simulate-delivered-2@notifications.service.gov.uk',
        grade: 'PO',
        workload: 100,
        casesPastWeek: 20,
        communityCases: 10,
        custodyCases: 10,
        licenseCases: 4,
        allocatedCasesPastWeek: 10,
        reallocatedCasesPastWeek: 5,
        ispsDueInNext14Days: 4,
        activeCases: 23,
        contactSuspendedCases: 0,
        custodyReleasesInNext7Days: 1,
        paroleReportsInNext28Days: 5,
        otherReportsInNext14Days: 3,
        tierCaseTotals: {
          untiered: 0,
          a: 4,
          b: 5,
          c: 2,
          d: 2,
          as: 2,
          bs: 0,
          cs: 1,
          ds: 1,
        },
      },
      {
        code: 'N57A046',
        name: {
          forename: 'Samantha',
          surname: 'Bryant',
          combinedName: 'Samantha Bryant',
        },
        email: 'Samantha.Bryant@digital.justice.gov.uk',
        grade: 'PO',
        workload: 110,
        casesPastWeek: 21,
        communityCases: 11,
        custodyCases: 11,
        licenseCases: 2,
        allocatedCasesPastWeek: 11,
        reallocatedCasesPastWeek: 5,
        ispsDueInNext14Days: 5,
        activeCases: 24,
        contactSuspendedCases: 1,
        custodyReleasesInNext7Days: 2,
        paroleReportsInNext28Days: 0,
        otherReportsInNext14Days: 4,
        tierCaseTotals: {
          untiered: 1,
          a: 1,
          b: 6,
          c: 3,
          d: 3,
          as: 1,
          bs: 2,
          cs: 0,
          ds: 1,
        },
      },
      {
        code: 'N57A042',
        name: {
          forename: 'Pauline',
          surname: 'Silver',
          combinedName: 'Pauline Silver',
        },
        email: 'pauline.silver@digital.justice.gov.uk',
        grade: 'PO',
        workload: 120,
        casesPastWeek: 22,
        communityCases: 12,
        custodyCases: 12,
        licenseCases: 5,
        allocatedCasesPastWeek: 12,
        reallocatedCasesPastWeek: 6,
        ispsDueInNext14Days: 3,
        activeCases: 25,
        contactSuspendedCases: 2,
        custodyReleasesInNext7Days: 1,
        paroleReportsInNext28Days: 4,
        otherReportsInNext14Days: 0,
        tierCaseTotals: {
          untiered: 0,
          a: 2,
          b: 4,
          c: 6,
          d: 1,
          as: 2,
          bs: 1,
          cs: 1,
          ds: 2,
        },
      },
      {
        code: 'N57A024',
        name: {
          forename: 'Rose',
          surname: 'Brandle',
          combinedName: 'Rose Brandle',
        },
        email: 'rose.brandle@digital.justice.gov.uk',
        grade: 'PO',
        workload: 130,
        casesPastWeek: 23,
        communityCases: 13,
        custodyCases: 13,
        licenseCases: 6,
        allocatedCasesPastWeek: 13,
        reallocatedCasesPastWeek: 6,
        ispsDueInNext14Days: 6,
        activeCases: 26,
        contactSuspendedCases: 0,
        custodyReleasesInNext7Days: 2,
        paroleReportsInNext28Days: 2,
        otherReportsInNext14Days: 5,
        tierCaseTotals: {
          untiered: 2,
          a: 5,
          b: 3,
          c: 4,
          d: 2,
          as: 0,
          bs: 2,
          cs: 2,
          ds: 1,
        },
      },
      {
        code: 'N07B290',
        name: {
          forename: 'Andy',
          surname: 'Sweilam',
          combinedName: 'Andy Sweilam',
        },
        email: 'andy.sweilam@digital.justice.gov.uk',
        grade: 'PO',
        workload: 140,
        casesPastWeek: 24,
        communityCases: 14,
        custodyCases: 14,
        licenseCases: 7,
        allocatedCasesPastWeek: 14,
        reallocatedCasesPastWeek: 7,
        ispsDueInNext14Days: 4,
        activeCases: 27,
        contactSuspendedCases: 1,
        custodyReleasesInNext7Days: 0,
        paroleReportsInNext28Days: 3,
        otherReportsInNext14Days: 2,
        tierCaseTotals: {
          untiered: 1,
          a: 4,
          b: 5,
          c: 5,
          d: 1,
          as: 1,
          bs: 1,
          cs: 3,
          ds: 1,
        },
      },
    ],
  },
}

export default {
  stubForTeamWorkload: (): SuperAgentRequest => {
    return stubForWorkload({
      request: {
        method: 'GET',
        urlPattern: '/team/practitioner-workloadcases\\?teamCode=.*',
      },
      response: {
        status: 200,
        headers: { 'Content-Type': 'application/json;charset=UTF-8' },
        jsonBody: {
          N03F01: {
            teams: teamWorkload.N03F01.teams,
          },
        },
      },
    })
  },
  stubForTeamWorkloadOverCapacity: (): SuperAgentRequest => {
    return stubForWorkload({
      request: {
        method: 'GET',
        urlPattern: '/team/practitioner-workloadcases\\?teamCode=.*',
      },
      response: {
        status: 200,
        headers: { 'Content-Type': 'application/json;charset=UTF-8' },
        jsonBody: {
          N03F01: {
            teams: teamWorkload.N03F01.teams.map(team => ({
              ...team,
              workload: 150,
            })),
          },
        },
      },
    })
  },
  stubForTeamWorkloadZeroCapacities: (): SuperAgentRequest => {
    return stubForWorkload({
      request: {
        method: 'GET',
        urlPattern: '/team/practitioner-workloadcases\\?teamCode=.*',
      },
      response: {
        status: 200,
        headers: { 'Content-Type': 'application/json;charset=UTF-8' },
        jsonBody: {
          N03F01: {
            teams: teamWorkload.N03F01.teams.map((team, index) => ({
              ...team,
              workload: index < 4 ? 0 : 75,
            })),
          },
        },
      },
    })
  },
}
