---
# Per environment values which override defaults in manage-a-workforce-ui/values.yaml

generic-service:

  ingress:
    className: modsec-non-prod
    host: workforce-management-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://workforce-management-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    MANAGE_USERS_SERVICE_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    ALLOCATIONS_SERVICE_URL: "https://hmpps-allocations-preprod.hmpps.service.justice.gov.uk"
    WORKLOAD_MEASUREMENT_URL: "https://workload-measurement-preprod.hmpps.service.justice.gov.uk"
    WORKLOAD_SERVICE_URL: "https://hmpps-workload-preprod.hmpps.service.justice.gov.uk"
    PROBATION_ESTATE_SERVICE_URL: "https://hmpps-probation-estate-api-preprod.hmpps.service.justice.gov.uk"
    USER_PREFERENCE_SERVICE_URL: "https://hmpps-user-preferences-preprod.hmpps.service.justice.gov.uk"
    STAFF_LOOKUP_SERVICE_URL: "https://hmpps-staff-lookup-service-preprod.hmpps.service.justice.gov.uk"

  scheduledDowntime:
    enabled: true

generic-prometheus-alerts:
  businessHoursOnly: true
