---
# Per environment values which override defaults in manage-a-workforce-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-a-workforce-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://workforce-management-dev.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"

