---
# Per environment values which override defaults in manage-a-workforce-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: workforce-management-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://workforce-management-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ALLOCATIONS_SERVICE_URL: "https://hmpps-allocations-dev.hmpps.service.justice.gov.uk"
    WORKLOAD_MEASUREMENT_URL: "https://workload-measurement-dev.hmpps.service.justice.gov.uk"
    WORKLOAD_SERVICE_URL: "https://hmpps-workload-dev.hmpps.service.justice.gov.uk"
    PROBATION_ESTATE_SERVICE_URL: "https://hmpps-probation-estate-api-dev.hmpps.service.justice.gov.uk"
    USER_PREFERENCE_SERVICE_URL: "https://hmpps-user-preferences-dev.hmpps.service.justice.gov.uk"
    STAFF_LOOKUP_SERVICE_URL: "https://hmpps-staff-lookup-service-dev.hmpps.service.justice.gov.uk"
    SHOW_NOTIFICATION: "true"

  scheduledDowntime:
    enabled: true

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    ark-internet-1: "194.33.192.0/25"
    ark-internet-2: "194.33.196.0/25"
    global-protect: "35.176.93.186/32"
    moj-official-tgw-prod: "51.149.250.0/24"
    moj-official-tgw-preprod: "51.149.251.0/24"
    moj-official-ark-c-expo-e: "51.149.249.0/29"
    moj-official-ark-c-vodafone: "194.33.248.0/29"
    moj-official-ark-f-vodafone: "194.33.249.0/29"
    moj-official-ark-f-expo-e: "51.149.249.32/29"
    unilink-vpn-1: "194.75.210.216/29"
    unilink-vpn-2: "83.98.63.176/29"
    unilink-vpn-3: "78.33.10.50/31"
    unilink-vpn-4: "78.33.10.52/30"
    unilink-vpn-5: "78.33.10.56/30"
    unilink-vpn-6: "78.33.10.60/32"
    unilink-vpn-7: "78.33.32.99/32"
    unilink-vpn-8: "78.33.32.100/30"
    unilink-vpn-9: "78.33.32.104/30"
    unilink-vpn-10: "78.33.32.108/32"
    unilink-vpn-11: "217.138.45.109/32"
    unilink-vpn-12: "217.138.45.110/32"
