# Per environment values which override defaults in manage-a-workforce-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: workforce-management-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://workforce-management-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    MANAGE_USERS_SERVICE_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    ALLOCATIONS_SERVICE_URL: "https://hmpps-allocations-dev.hmpps.service.justice.gov.uk"
    WORKLOAD_MEASUREMENT_URL: "https://workload-measurement-dev.hmpps.service.justice.gov.uk"
    WORKLOAD_SERVICE_URL: "https://hmpps-workload-dev.hmpps.service.justice.gov.uk"
    PROBATION_ESTATE_SERVICE_URL: "https://hmpps-probation-estate-api-dev.hmpps.service.justice.gov.uk"
    USER_PREFERENCE_SERVICE_URL: "https://hmpps-user-preferences-dev.hmpps.service.justice.gov.uk"
    STAFF_LOOKUP_SERVICE_URL: "https://hmpps-staff-lookup-service-dev.hmpps.service.justice.gov.uk"

  scheduledDowntime:
    enabled: true

  allowlist:
    unilink-aovpn1: 194.75.210.216/29
    unilink-aovpn3: 78.33.10.50/31
    unilink-aovpn4: 78.33.10.52/30
    unilink-aovpn5: 78.33.10.56/30
    unilink-aovpn6: 78.33.10.60/32
    unilink-aovpn7: 78.33.32.99/32
    unilink-aovpn8: 78.33.32.100/30
    unilink-aovpn9: 78.33.32.104/30
    unilink-aovpn10: 78.33.32.108/32
    groups:
      - internal
      - prisons
      - unilink_staff
