---
# Per environment values which override defaults in manage-a-workforce-ui/values.yaml

generic-service:
  replicaCount: 3

  ingress:
    className: modsec
    host: workforce-management.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://workforce-management.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    MANAGE_USERS_SERVICE_URL: "https://manage-users-api.hmpps.service.justice.gov.uk"
    ALLOCATIONS_SERVICE_URL: "https://hmpps-allocations.hmpps.service.justice.gov.uk"
    WORKLOAD_MEASUREMENT_URL: "https://workload-measurement.hmpps.service.justice.gov.uk"
    WORKLOAD_SERVICE_URL: "https://hmpps-workload.hmpps.service.justice.gov.uk"
    PROBATION_ESTATE_SERVICE_URL: "https://hmpps-probation-estate-api.hmpps.service.justice.gov.uk"
    USER_PREFERENCE_SERVICE_URL: "https://hmpps-user-preferences.hmpps.service.justice.gov.uk"
    STAFF_LOOKUP_SERVICE_URL: "https://hmpps-staff-lookup-service.hmpps.service.justice.gov.uk"
    FLIPT_URL: "https://feature-toggles.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: workforce-management-prod-alerts
  ingress5xxErrorWindowMinutes: 4
