---
# Per environment values which override defaults in manage-a-workforce-ui/values.yaml

generic-service:

  ingress:
    host: workforce-management.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://workforce-management.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    ALLOCATIONS_SERVICE_URL: "https://hmpps-allocations.hmpps.service.justice.gov.uk"

